# Generated by Django 5.2.4 on 2025-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment140Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(choices=[(0, 'negative'), (2, 'neutral'), (4, 'positive')])),
                ('tweet_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('flag', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=15)),
                ('text', models.TextField(max_length=280)),
            ],
        ),
    ]
