# Generated by Django 5.2.4 on 2025-07-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibechecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment140item',
            name='tweet_id',
            field=models.IntegerField(),
        ),
    ]
