# Generated by Django 5.2.4 on 2025-08-20 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibechecker', '0002_remove_registereduser_test_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentresponseitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
